import './globals.css'
import { Nunito } from 'next/font/google'
import Navbar from './components/navbar/Navbar'



import RegisterModal from './components/modals/RegisterModal'
import ClientOnly from './components/ClientOnly'
import ToasterProvider from './provider/ToasterProvider'
import LoginModal from './components/modals/LoginModal'
import getcurrentUser from './actions/getcurrentuser'
import RentModal from './components/modals/RentModal'

const font = Nunito({
  subsets: ["latin"]
})

export const metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}



export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getcurrentUser();

  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <RentModal />
          <LoginModal />
          <RegisterModal />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
